version: "3"
services:

 web:
  image: nginx
  container_name: nginx
  networks:
   mynet:
    ipv4_address: 172.28.0.2
  ports:
   - "80:80"
  volumes:
   - ../web_conf/default.conf:/etc/nginx/conf.d/default.conf
   - ../web_root:/usr/share/nginx/html
 # restart: on-failure
#  links:
#   - app

 app:
  image: node
  container_name: node
  networks:
   mynet:
    ipv4_address: 172.28.0.3
  ports:
   - 8081:8081
  working_dir: /app
  volumes:
   - ../app_root:/app
  command: bash -c "npm install mysql http && node index.js"
  environment:
   - NODE_ENV=production
#  links:
#   - db
  depends_on:
   - db
#  restart: on-failure

 db:
  image: mariadb
  container_name: mariadb
  networks:
   mynet:
    ipv4_address: 172.28.0.4
  ports:
   - 3307:3306
  volumes:
   - ../db:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: db_password!@
   MYSQL_DATABASE: model_designer
   MYSQL_USER: model_designer
   MYSQL_PASSWORD: mdesigner!@#
#  restart: on-failure

volumes:
  mariadb:

networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16